adds missing dep
apostrophecms/import-export pull request #37
Opened 2023-10-17 09:35 UTC by ValJed

Add missing dep with same version than in core.

2023-10-18 09:19 UTC, ETLaurent approved these changes

2023-10-18 09:20 UTC, ETLaurent requested changes

2023-10-18 09:20 UTC, ETLaurent commented on CHANGELOG.md
> +* Adds missing dependency.
```suggestion
### Fixes

* Adds missing dependency.
```

2023-11-01 14:25 UTC, falkodev approved these changes

2023-11-01 14:31 UTC, merged