PRO-6561: export documents which are related via rich text widget "internal pages" links and inline images
apostrophecms/import-export pull request #98
Opened 2024-12-02 19:03 UTC by boutell

## Summary

See changelog and title.

## What are the specific steps to test this change?

* See unit tests
* Can also try the feature (add `insert: [ 'image' ]` to rich text widget config, add an inline image, add an "Internal Page" link to another page — do not paste a URL, that does not count)

## What kind of change does this PR introduce?
*(Check at least one)*

- [X] Bug fix
- [X] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [X] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-12-09 10:10 UTC, ValJed commented on lib/methods/export.js
> +      if ((rteOptions.toolbar?.includes('image') || rteOptions.insert?.includes('image')) && !related.includes('@apostrophecms/image')) {
Please indentation:
```javascript
      if (
        (rteOptions.toolbar?.includes('image') || rteOptions.insert?.includes('image')) &&
        !related.includes('@apostrophecms/image')
      ) {
```

2024-12-09 10:21 UTC, ValJed commented
Minor feedback, feature tested it seems working.
Could run cypress tests?

2024-12-09 13:41 UTC, boutell commented on lib/methods/export.js
> +      }
Done

2024-12-09 13:42 UTC, boutell commented on lib/methods/export.js
> +        }
Done

2024-12-09 13:43 UTC, boutell commented on lib/methods/export.js
> +      if ((rteOptions.toolbar?.includes('image') || rteOptions.insert?.includes('image')) && !related.includes('@apostrophecms/image')) {
done

2024-12-09 14:21 UTC, ValJed commented on lib/methods/export.js
> +        });
Ok makes sense then

2024-12-09 14:22 UTC, ValJed approved these changes

2024-12-18 14:57 UTC, ValJed requested changes
Tiny things,
I tested quickly and saw that:
![image](https://github.com/user-attachments/assets/e2a26801-0025-4a4e-9e08-bf9762486703)

I don't think we should see `@apostrophecms/archive-page`?

2024-12-18 14:57 UTC, ValJed commented on lib/methods/export.js
> +      linkedDocs = linkedDocs.filter(doc => relatedTypes.includes(doc.type));
Why not checking types direclty in the find request above?

2024-12-18 14:57 UTC, ValJed commented on lib/methods/export.js
> +        const pageTypes = Object.entries(self.apos.doc.managers).filter(([ name, module ]) => self.apos.instanceOf(module, '@apostrophecms/page-type')).map(([ name, module ]) => name);
This line is 184 chars 😮  ahah
Please indentate

2025-01-02 20:21 UTC, boutell commented on lib/methods/export.js
> +      linkedDocs = linkedDocs.filter(doc => relatedTypes.includes(doc.type));
This logic is sound and I hesitate to start changing the query logic at this point. Only document ids that were actually linked are going to be queried for, so it's not critical to turn this into a mongo filter as long as we do filter it here.

2025-01-02 20:21 UTC, boutell commented on lib/methods/export.js
> +        const pageTypes = Object.entries(self.apos.doc.managers).filter(([ name, module ]) => self.apos.instanceOf(module, '@apostrophecms/page-type')).map(([ name, module ]) => name);
Done.

2025-01-06 15:32 UTC, ValJed approved these changes

2025-01-06 15:33 UTC, merged